# -*- coding: utf-8 -*-
"""automated_revenue_profit_monitoring_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVhKLTUhemB8yM9qtKm3MFln8CKFjlw8

# Automated Revenue & Profit Monitoring System

## Project Overview

This project builds an automated business reporting workflow for Superstore sales data. The goal is to move beyond basic analysis and create a repeatable monitoring system that can combine monthly sales files, validate data quality, calculate revenue and profitability KPIs, detect business risks, and export final reports for stakeholders.

## Business Problem

Sales teams often receive transaction data in separate monthly files. Manually combining files, checking data quality, calculating KPIs, and preparing reports takes time and can introduce errors. This project automates that workflow and produces consistent monthly performance outputs.

## Tools Used

- Python
- pandas
- matplotlib
- Google Colab

## Key Outputs

- Cleaned combined sales dataset
- Monthly KPI summary
- Data validation summary
- Revenue and profit risk alerts
- Category and region performance summaries
- Visual charts
- Business insight text report
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

file_path = "sample_-_superstore.xls"

df = pd.read_excel(file_path)

print("Dataset shape:", df.shape)
df.head()

!pip install xlrd

df = pd.read_excel("sample_-_superstore.xls")
df.head()

df.info()

df.columns

df.isnull().sum()

required_columns = [
    "Order Date", "Ship Date", "Region", "Category", "Sub-Category",
    "Product Name", "Sales", "Quantity", "Discount", "Profit"
]

for col in required_columns:
    print(col, ":", col in df.columns)

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

print("Date range:")
print(df["Order Date"].min(), "to", df["Order Date"].max())

df.shape
df.columns
df.isnull().sum()

"""## Data Preparation and Monthly File Simulation

After loading and inspecting the dataset, the date fields are converted into proper datetime format. Additional reporting columns such as year, month, month-year, and shipping days are created.

To demonstrate automation, the original dataset is split into multiple monthly CSV files. This simulates a real reporting process where new sales files arrive every month.

"""

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month_Year"] = df["Order Date"].dt.to_period("M").astype(str)

df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

print("Date range:", df["Order Date"].min(), "to", df["Order Date"].max())
print("Shape:", df.shape)

df[["Order Date", "Ship Date", "Year", "Month", "Month_Year", "Shipping Days"]].head()

"""### Create Monthly CSV Files

The dataset is grouped by month and exported into separate CSV files. These files represent recurring monthly sales extracts that an analyst might receive from a business system.

"""

import os

monthly_folder = "monthly_sales_files"
os.makedirs(monthly_folder, exist_ok=True)

for month, month_df in df.groupby("Month_Year"):
    file_name = f"sales_{month}.csv"
    file_path = os.path.join(monthly_folder, file_name)
    month_df.to_csv(file_path, index=False)

print("Monthly CSV files created:", len(os.listdir(monthly_folder)))
os.listdir(monthly_folder)[:5]

"""### Combine Monthly Files Automatically

The script reads every CSV file from the monthly folder and combines them into a single dataframe. This removes manual copy-paste work and makes the workflow reusable for future monthly files.

"""

import glob

csv_files = glob.glob("monthly_sales_files/*.csv")

combined_df = pd.concat(
    [pd.read_csv(file) for file in csv_files],
    ignore_index=True
)

print("Combined shape:", combined_df.shape)
combined_df.head()

"""## Data Validation Checks

Before calculating KPIs, the pipeline validates whether the dataset is reliable enough for reporting. These checks help catch missing columns, duplicate rows, invalid dates, negative sales values, invalid discounts, and incorrect shipping dates.

"""

# Convert date columns again after reading combined CSV files
combined_df["Order Date"] = pd.to_datetime(combined_df["Order Date"])
combined_df["Ship Date"] = pd.to_datetime(combined_df["Ship Date"])

# Required columns for this project
required_columns = [
    "Order ID", "Order Date", "Ship Date", "Region", "Category",
    "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"
]

validation_results = {}

# 1. Check missing required columns
missing_columns = [col for col in required_columns if col not in combined_df.columns]
validation_results["missing_required_columns"] = missing_columns

# 2. Check missing values
validation_results["missing_values"] = combined_df[required_columns].isnull().sum()

# 3. Check duplicate rows
validation_results["duplicate_rows"] = combined_df.duplicated().sum()

# 4. Check invalid sales/quantity values
validation_results["negative_sales_count"] = (combined_df["Sales"] < 0).sum()
validation_results["zero_or_negative_quantity_count"] = (combined_df["Quantity"] <= 0).sum()

# 5. Check discount outside expected range
validation_results["invalid_discount_count"] = (
    (combined_df["Discount"] < 0) | (combined_df["Discount"] > 1)
).sum()

# 6. Check shipping date before order date
validation_results["invalid_shipping_dates_count"] = (
    combined_df["Ship Date"] < combined_df["Order Date"]
).sum()

validation_results

"""### Validation Summary

The validation results are converted into a readable summary table. This gives stakeholders confidence that the reporting output is based on clean and consistent data.

"""

validation_summary = pd.DataFrame({
    "Check": [
        "Missing required columns",
        "Duplicate rows",
        "Negative sales records",
        "Zero/negative quantity records",
        "Invalid discount records",
        "Invalid shipping dates"
    ],
    "Result": [
        len(missing_columns),
        validation_results["duplicate_rows"],
        validation_results["negative_sales_count"],
        validation_results["zero_or_negative_quantity_count"],
        validation_results["invalid_discount_count"],
        validation_results["invalid_shipping_dates_count"]
    ]
})

validation_summary

"""## KPI Calculation

This section calculates the core business metrics used for revenue and profitability monitoring: total sales, total profit, order count, quantity sold, average order value, profit margin, and average discount.

"""

# Basic KPI calculations
total_sales = combined_df["Sales"].sum()
total_profit = combined_df["Profit"].sum()
total_orders = combined_df["Order ID"].nunique()
total_quantity = combined_df["Quantity"].sum()
average_order_value = total_sales / total_orders
profit_margin = total_profit / total_sales
average_discount = combined_df["Discount"].mean()

kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Sales",
        "Total Profit",
        "Total Orders",
        "Total Quantity Sold",
        "Average Order Value",
        "Profit Margin",
        "Average Discount"
    ],
    "Value": [
        total_sales,
        total_profit,
        total_orders,
        total_quantity,
        average_order_value,
        profit_margin,
        average_discount
    ]
})

kpi_summary

"""### Monthly KPI Summary

The monthly KPI table tracks performance over time. It includes sales, profit, order volume, quantity, discount, profit margin, average order value, and month-over-month growth rates.

"""

monthly_kpi = combined_df.groupby("Month_Year").agg(
    total_sales=("Sales", "sum"),
    total_profit=("Profit", "sum"),
    total_orders=("Order ID", "nunique"),
    total_quantity=("Quantity", "sum"),
    avg_discount=("Discount", "mean")
).reset_index()

monthly_kpi["profit_margin"] = monthly_kpi["total_profit"] / monthly_kpi["total_sales"]
monthly_kpi["average_order_value"] = monthly_kpi["total_sales"] / monthly_kpi["total_orders"]

monthly_kpi["sales_growth_pct"] = monthly_kpi["total_sales"].pct_change() * 100
monthly_kpi["profit_growth_pct"] = monthly_kpi["total_profit"].pct_change() * 100

monthly_kpi.head()

"""### Review Monthly Performance

The full monthly summary is reviewed to understand trends and prepare for monthly alert detection.

"""

monthly_kpi

"""## Business Risk Detection

This is the main value-add section of the project. Instead of only reporting what happened, the notebook applies rule-based logic to flag potential business risks such as high sales with weak profit, loss-making products, high discount losses, and weak category or region margins.

"""

# Product-level performance
product_perf = combined_df.groupby(["Product Name", "Category", "Sub-Category"]).agg(
    total_sales=("Sales", "sum"),
    total_profit=("Profit", "sum"),
    total_quantity=("Quantity", "sum"),
    avg_discount=("Discount", "mean"),
    total_orders=("Order ID", "nunique")
).reset_index()

product_perf["profit_margin"] = product_perf["total_profit"] / product_perf["total_sales"]

product_perf.head()

"""### Alert 1: High Sales but Low Profit

This alert identifies products with strong revenue but weak profitability. These products may look successful from a sales perspective but may not be contributing enough profit.

"""

high_sales_threshold = product_perf["total_sales"].quantile(0.75)

high_sales_low_profit = product_perf[
    (product_perf["total_sales"] >= high_sales_threshold) &
    (product_perf["profit_margin"] < 0.05)
].sort_values("total_sales", ascending=False)

high_sales_low_profit.head(10)

"""### Alert 2: Loss-Making Products

This alert lists products where total profit is negative. These items may need pricing review, discount control, supplier review, or removal from priority sales campaigns.

"""

loss_making_products = product_perf[
    product_perf["total_profit"] < 0
].sort_values("total_profit")

loss_making_products.head(10)

"""### Alert 3: High Discount and Negative Profit

This alert checks whether heavy discounting is linked with products that lose money. It helps identify where discount strategy may be damaging profitability.

"""

high_discount_loss = product_perf[
    (product_perf["avg_discount"] >= 0.30) &
    (product_perf["total_profit"] < 0)
].sort_values("avg_discount", ascending=False)

high_discount_loss.head(10)

"""### Alert 4: Category-Level Risk

Category-level performance is reviewed to compare sales, profit, average discount, and profit margin across major product groups.

"""

category_risk = combined_df.groupby("Category").agg(
    total_sales=("Sales", "sum"),
    total_profit=("Profit", "sum"),
    avg_discount=("Discount", "mean"),
    total_quantity=("Quantity", "sum")
).reset_index()

category_risk["profit_margin"] = category_risk["total_profit"] / category_risk["total_sales"]

category_risk.sort_values("profit_margin")

"""### Alert 5: Region-Level Risk

Region-level performance is reviewed to identify markets with high sales but weaker profitability or unusually high discount levels.

"""

region_risk = combined_df.groupby("Region").agg(
    total_sales=("Sales", "sum"),
    total_profit=("Profit", "sum"),
    avg_discount=("Discount", "mean"),
    total_orders=("Order ID", "nunique")
).reset_index()

region_risk["profit_margin"] = region_risk["total_profit"] / region_risk["total_sales"]

region_risk.sort_values("profit_margin")

"""**Interview Talking Point**

This project does not stop at descriptive reporting. It uses rule-based alerts to identify products, categories, regions, and months where revenue performance may hide profitability risk.

## Monthly Performance Alerts

This section compares each month with the previous month and flags sharp drops in sales, profit, or profit margin. This is useful for monthly business review meetings and early performance monitoring.
"""

monthly_alerts = monthly_kpi.copy()

monthly_alerts["margin_change_pct"] = monthly_alerts["profit_margin"].pct_change() * 100

monthly_alerts["sales_alert"] = monthly_alerts["sales_growth_pct"].apply(
    lambda x: "Sales Drop" if x < -10 else "Normal"
)

monthly_alerts["profit_alert"] = monthly_alerts["profit_growth_pct"].apply(
    lambda x: "Profit Drop" if x < -10 else "Normal"
)

monthly_alerts["margin_alert"] = monthly_alerts["margin_change_pct"].apply(
    lambda x: "Margin Drop" if x < -10 else "Normal"
)

monthly_alerts[
    ["Month_Year", "total_sales", "total_profit", "profit_margin",
     "sales_growth_pct", "profit_growth_pct", "margin_change_pct",
     "sales_alert", "profit_alert", "margin_alert"]
].head()

"""### Risky Months

Only months with meaningful performance drops are filtered into a separate table so stakeholders can focus on exceptions instead of reviewing every month manually.

"""

risky_months = monthly_alerts[
    (monthly_alerts["sales_alert"] != "Normal") |
    (monthly_alerts["profit_alert"] != "Normal") |
    (monthly_alerts["margin_alert"] != "Normal")
]

risky_months[
    ["Month_Year", "sales_growth_pct", "profit_growth_pct", "margin_change_pct",
     "sales_alert", "profit_alert", "margin_alert"]
]

"""### Alert Summary

The alert summary gives a quick count of detected risk areas across products and months.

"""

alert_summary = pd.DataFrame({
    "Alert Type": [
        "High sales but low profit products",
        "Loss-making products",
        "High discount loss products",
        "Risky months"
    ],
    "Count": [
        len(high_sales_low_profit),
        len(loss_making_products),
        len(high_discount_loss),
        len(risky_months)
    ]
})

alert_summary

"""## Data Visualization

The charts below convert the KPI and alert tables into visuals that can be used in a portfolio, presentation, or stakeholder report.

"""

import os
import matplotlib.pyplot as plt

charts_folder = "charts"
os.makedirs(charts_folder, exist_ok=True)

"""### Monthly Sales Trend

This line chart shows how total sales changed over time.

"""

plt.figure(figsize=(12, 5))
plt.plot(monthly_kpi["Month_Year"], monthly_kpi["total_sales"], marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("charts/monthly_sales_trend.png", dpi=300)
plt.show()

"""### Monthly Profit Trend

This line chart shows how total profit changed over time.

"""

plt.figure(figsize=(12, 5))
plt.plot(monthly_kpi["Month_Year"], monthly_kpi["total_profit"], marker="o", color="green")
plt.title("Monthly Profit Trend")
plt.xlabel("Month")
plt.ylabel("Total Profit")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("charts/monthly_profit_trend.png", dpi=300)
plt.show()

"""### Profit Margin by Category

This chart compares category-level profitability, helping identify which categories are most and least efficient at converting sales into profit.

"""

category_risk_sorted = category_risk.sort_values("profit_margin", ascending=False)

plt.figure(figsize=(8, 5))
plt.bar(category_risk_sorted["Category"], category_risk_sorted["profit_margin"])
plt.title("Profit Margin by Category")
plt.xlabel("Category")
plt.ylabel("Profit Margin")
plt.tight_layout()
plt.savefig("charts/profit_margin_by_category.png", dpi=300)
plt.show()

"""### Sales vs Profit by Region

This chart compares regional revenue with profit to highlight whether high-sales regions are also profitable.

"""

region_risk_sorted = region_risk.sort_values("total_sales", ascending=False)

x = range(len(region_risk_sorted))

plt.figure(figsize=(9, 5))
plt.bar(x, region_risk_sorted["total_sales"], label="Sales")
plt.bar(x, region_risk_sorted["total_profit"], label="Profit")
plt.xticks(x, region_risk_sorted["Region"])
plt.title("Sales vs Profit by Region")
plt.xlabel("Region")
plt.ylabel("Amount")
plt.legend()
plt.tight_layout()
plt.savefig("charts/sales_vs_profit_by_region.png", dpi=300)
plt.show()

"""### Top 10 Loss-Making Products

This chart highlights the products with the largest negative profit contribution.

"""

top_losses = loss_making_products.head(10)

plt.figure(figsize=(12, 6))
plt.barh(top_losses["Product Name"], top_losses["total_profit"], color="red")
plt.title("Top 10 Loss-Making Products")
plt.xlabel("Total Profit")
plt.ylabel("Product Name")
plt.tight_layout()
plt.savefig("charts/top_loss_making_products.png", dpi=300)
plt.show()

"""### Saved Chart Files

The chart folder is checked to confirm that all visualization files were created successfully.

"""

os.listdir("charts")

"""## Export Final Reports

The final output tables are saved as CSV files. This makes the project usable as a repeatable reporting workflow, not just a one-time notebook analysis.

"""

output_folder = "output_reports"
os.makedirs(output_folder, exist_ok=True)

"""### Export KPI and Risk Tables

The cleaned dataset, validation results, KPI summaries, risk tables, and monthly alerts are exported for business review or dashboard use.

"""

kpi_summary.to_csv("output_reports/kpi_summary.csv", index=False)
monthly_kpi.to_csv("output_reports/monthly_kpi_summary.csv", index=False)
validation_summary.to_csv("output_reports/data_validation_summary.csv", index=False)

high_sales_low_profit.to_csv("output_reports/high_sales_low_profit_products.csv", index=False)
loss_making_products.to_csv("output_reports/loss_making_products.csv", index=False)
high_discount_loss.to_csv("output_reports/high_discount_loss_products.csv", index=False)

category_risk.to_csv("output_reports/category_risk_summary.csv", index=False)
region_risk.to_csv("output_reports/region_risk_summary.csv", index=False)
risky_months.to_csv("output_reports/risky_months.csv", index=False)

combined_df.to_csv("output_reports/cleaned_combined_sales_data.csv", index=False)

"""### Review Exported Files

The output folder is checked to confirm that all final report files were created successfully.

"""

os.listdir("output_reports")

"""### Combined Business Risk Alert File

A single alert file is created by combining the most important product-level and month-level risks. This gives stakeholders one focused exception report.

"""

alerts = []

for _, row in high_sales_low_profit.head(10).iterrows():
    alerts.append({
        "Alert Type": "High Sales Low Profit",
        "Entity": row["Product Name"],
        "Category": row["Category"],
        "Sales": row["total_sales"],
        "Profit": row["total_profit"],
        "Profit Margin": row["profit_margin"],
        "Reason": "Product has high sales but weak profit margin"
    })

for _, row in loss_making_products.head(10).iterrows():
    alerts.append({
        "Alert Type": "Loss Making Product",
        "Entity": row["Product Name"],
        "Category": row["Category"],
        "Sales": row["total_sales"],
        "Profit": row["total_profit"],
        "Profit Margin": row["profit_margin"],
        "Reason": "Product generated negative profit"
    })

for _, row in risky_months.iterrows():
    alerts.append({
        "Alert Type": "Monthly Performance Risk",
        "Entity": row["Month_Year"],
        "Category": "Overall Business",
        "Sales": row["total_sales"],
        "Profit": row["total_profit"],
        "Profit Margin": row["profit_margin"],
        "Reason": f"{row['sales_alert']}, {row['profit_alert']}, {row['margin_alert']}"
    })

alerts_df = pd.DataFrame(alerts)

alerts_df.to_csv("output_reports/business_risk_alerts.csv", index=False)

alerts_df.head()

"""## Automated Business Insights

This section converts the analysis outputs into plain-language insights. These insights can be used in the project README, resume discussion, or interview explanation.

"""

# Best and worst months
best_sales_month = monthly_kpi.loc[monthly_kpi["total_sales"].idxmax()]
worst_sales_month = monthly_kpi.loc[monthly_kpi["total_sales"].idxmin()]

best_profit_month = monthly_kpi.loc[monthly_kpi["total_profit"].idxmax()]
worst_profit_month = monthly_kpi.loc[monthly_kpi["total_profit"].idxmin()]

# Best and weakest categories
best_category_sales = category_risk.loc[category_risk["total_sales"].idxmax()]
weakest_category_margin = category_risk.loc[category_risk["profit_margin"].idxmin()]

# Best and weakest regions
best_region_sales = region_risk.loc[region_risk["total_sales"].idxmax()]
weakest_region_margin = region_risk.loc[region_risk["profit_margin"].idxmin()]

# Discount impact
avg_discount_loss_products = loss_making_products["avg_discount"].mean()
avg_discount_profitable_products = product_perf[product_perf["total_profit"] > 0]["avg_discount"].mean()

insights = [
    f"Highest sales month was {best_sales_month['Month_Year']} with total sales of {best_sales_month['total_sales']:.2f}.",
    f"Lowest sales month was {worst_sales_month['Month_Year']} with total sales of {worst_sales_month['total_sales']:.2f}.",
    f"Highest profit month was {best_profit_month['Month_Year']} with total profit of {best_profit_month['total_profit']:.2f}.",
    f"Lowest profit month was {worst_profit_month['Month_Year']} with total profit of {worst_profit_month['total_profit']:.2f}.",
    f"{best_category_sales['Category']} generated the highest sales among categories.",
    f"{weakest_category_margin['Category']} had the weakest profit margin among categories.",
    f"{best_region_sales['Region']} generated the highest sales among regions.",
    f"{weakest_region_margin['Region']} had the weakest profit margin among regions.",
    f"Loss-making products had an average discount of {avg_discount_loss_products:.2%}, compared with {avg_discount_profitable_products:.2%} for profitable products.",
    f"The monitoring system detected {len(risky_months)} risky months and {len(loss_making_products)} loss-making products."
]

for insight in insights:
    print("-", insight)

"""### Save Business Insights

The generated business insights are saved as a text file so they can be shared with the exported reports.

"""

with open("output_reports/business_insights.txt", "w") as file:
    for insight in insights:
        file.write("- " + insight + "\n")

"""### Review Insight Report

The final insight report is printed to confirm that the automated summary was generated correctly.

"""

with open("output_reports/business_insights.txt", "r") as file:
    print(file.read())

"""## Conclusion

This notebook demonstrates an end-to-end automated reporting workflow for revenue and profit monitoring. It combines monthly files, validates data quality, calculates business KPIs, detects performance risks, creates visual reports, and exports stakeholder-ready outputs.

The project is designed to show practical data analyst skills: automation, data cleaning, KPI reporting, profitability analysis, exception reporting, and business communication.

"""